server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: debug
      apache:
        http: debug